# Generated by Django 5.2 on 2025-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=100, null=True),
        ),
    ]
