# Generated by Django 5.2 on 2025-06-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assistance_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
