# Generated by Django 5.2 on 2025-06-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assistance_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('heavy', 'Heavy')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=100, null=True),
        ),
    ]
