# Generated by Django 5.2 on 2025-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_location_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='assistance_type',
            field=models.CharField(choices=[('repair', 'Repair'), ('towing', 'Towing')], default='towing'),
            preserve_default=False,
        ),
    ]
