# Generated by Django 5.2 on 2025-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assistance_assistance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistance',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('heavy', 'Heavy')], max_length=100, null=True),
        ),
    ]
