# Generated by Django 5.2 on 2025-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assistance_description_assistance_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
