name: depannini_user

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  onboarding: ^4.0.2
  email_otp: ^3.0.2
  get: ^4.7.2
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  pinput: ^5.0.1
  email_validator: ^3.0.0
  toggle_switch: ^2.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_maps_flutter: ^2.12.1
  location: ^8.0.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#d70005"
  image: "assets/images/logo_red.png"
  android_12:
    image: "assets/images/logo_red.png"
    icon_background_color: "#d70005"

  android: true
  ios: true
  web: false
  fullscreen: true