POST http://localhost:8000/api/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "name": "anes",
    "password": "test",
    "password_confirm": "test",
    "phone_number": "+213783072562",
    "user_type": "client"
}
###
POST http://localhost:8000/api/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "name": "anes",
    "password": "test",
    "password_confirm": "test",
    "phone_number": "+213783961958",
    "user_type": "client"
}

###
POST http://localhost:8000/api/auth/verify-phone/ HTTP/1.1
Content-Type: application/json

{
    "phone_number" : "+213783072562"
}

###


POST http://localhost:8000/api/auth/verify-email/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3OTM1ODUzLCJpYXQiOjE3NDczMzEwNTMsImp0aSI6IjM4MWRmNDIzMjAyODRiYWY5ZDliYWE2ODVkMTQ0YTkxIiwidXNlcl9pZCI6MTh9.M8sSNcV9ON1VBS_L9HHjYb3y1-pvXIpvMSjgHs5TS6w

###


POST http://localhost:8000/api/auth/verify-email/confirm/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3OTM1ODUzLCJpYXQiOjE3NDczMzEwNTMsImp0aSI6IjM4MWRmNDIzMjAyODRiYWY5ZDliYWE2ODVkMTQ0YTkxIiwidXNlcl9pZCI6MTh9.M8sSNcV9ON1VBS_L9HHjYb3y1-pvXIpvMSjgHs5TS6w

{
    "code" : 14884
}
###
POST http://localhost:8000/api/auth/password-reset/ HTTP/1.1
Content-Type: application/json

{
    "phone_number": "+213783072562"
}

###


POST http://localhost:8000/api/auth/password-reset/confirm/ HTTP/1.1
Content-Type: application/json

{
    "new_password" : "testing",
    "new_password_confirm" : "testing",
    "phone_number": "+213783072562",
    "code" : "84766"
}
###

POST http://localhost:8000/api/auth/login/phone/ HTTP/1.1
Content-Type: application/json

{
    "phone_number": "+1234567890",
    "password": "test"
}

###

POST http://localhost:8000/api/auth/login/email/ HTTP/1.1
Content-Type: application/json

{
    "email": "assistant1@example.com",
    "password": "test"
}

###
GET http://localhost:8000/api/profile/user/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3OTM1ODUzLCJpYXQiOjE3NDczMzEwNTMsImp0aSI6IjM4MWRmNDIzMjAyODRiYWY5ZDliYWE2ODVkMTQ0YTkxIiwidXNlcl9pZCI6MTh9.M8sSNcV9ON1VBS_L9HHjYb3y1-pvXIpvMSjgHs5TS6w
###
get http://localhost:8000/api/assistants/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NjA0NzM4LCJpYXQiOjE3NDU2MDExMzgsImp0aSI6IjYwZDhmZjFkYzNiYTRiYzFiM2M4NjcxM2U0MzMwODliIiwidXNlcl9pZCI6MTd9.M_wXq0cwnGrsa43GICE--E6YUs7eQbFKc6qqrSoTMhk

{
    "vehicle_registration_num": "4342342"
}

###

POST http://localhost:8000/api/assistance/request/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDQwNzgxLCJpYXQiOjE3NDg0MzU5ODEsImp0aSI6ImRiYmY1MTAxYmJlYjQ3NWFiOTY2OGE2YTgyYjIzMGM3IiwidXNlcl9pZCI6Mn0.7M4TMV5FB63lOX6Jqrc1ysbC9weUnwaVeemdfmRpg94

{
    "pickup": {
        "lat" : 34.052235,
        "lng" : -118.243683
    },
    "assistance_type": "towing",
    "dropoff": {
        "lat" : 34.085652,
        "lng" : -118.232176
    },
    "vehicle_type" : "heavy"
}

###

Patch http://localhost:8000/api/assistance/accept/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTc2MDU3LCJpYXQiOjE3NDgzNzEyNTcsImp0aSI6IjNhYmRhYjg1N2Y5NjQ1ZDk4Mzg2OWYyZDU3MWY1YTM2IiwidXNlcl9pZCI6MjF9.jERb-hxATE3kF0en1iwa-a73-paDirT50VQ6LqGpIRQ
### assistant update

Patch http://localhost:8000/api/assistance/update/status/32/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MjkxMTAxLCJpYXQiOjE3NDU2ODYzMDEsImp0aSI6IjRmM2U0YjEzOTRjNDQ3MmFhODQ4ODBmZTdkNGU3MjUyIiwidXNlcl9pZCI6MTd9.vUINAeoFTlw7OSluueNXOIE3rLBFYHaYz5KZSSsTkPo

{
    "status" : "canceled"
}

### status update

Patch http://localhost:8000/api/assistance/update/status/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTc2MDU3LCJpYXQiOjE3NDgzNzEyNTcsImp0aSI6IjNhYmRhYjg1N2Y5NjQ1ZDk4Mzg2OWYyZDU3MWY1YTM2IiwidXNlcl9pZCI6MjF9.jERb-hxATE3kF0en1iwa-a73-paDirT50VQ6LqGpIRQ

{
    "status" : "completed"
}

### price update

Patch http://localhost:8000/api/assistance/update/price/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTc2MDU3LCJpYXQiOjE3NDgzNzEyNTcsImp0aSI6IjNhYmRhYjg1N2Y5NjQ1ZDk4Mzg2OWYyZDU3MWY1YTM2IiwidXNlcl9pZCI6MjF9.jERb-hxATE3kF0en1iwa-a73-paDirT50VQ6LqGpIRQ

{
    "price" : "1800.34"
}

### rating update

Patch http://localhost:8000/api/assistance/update/rating/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDI3MDMzLCJpYXQiOjE3NDg0MjIyMzMsImp0aSI6IjAzZTA3ZmMwMDEzYTRhN2FhYjdhOGFlNDBhM2Q1MTU1IiwidXNlcl9pZCI6MTh9.SzXlG2CLN6ZsBaZBvPwAA6C102zT-qHSUs9iMo0P4X4

{
    "rating" : "3.5"
}

###
GET http://localhost:8000/api/assistance/view/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTc2MDU3LCJpYXQiOjE3NDgzNzEyNTcsImp0aSI6IjNhYmRhYjg1N2Y5NjQ1ZDk4Mzg2OWYyZDU3MWY1YTM2IiwidXNlcl9pZCI6MjF9.jERb-hxATE3kF0en1iwa-a73-paDirT50VQ6LqGpIRQ