POST http://localhost:8000/api/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "name": "anes",
    "password": "test",
    "password_confirm": "test",
    "phone_number": "+213783072562",
    "user_type": "client"
}

###
POST http://localhost:8000/api/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "name": "anes",
    "password": "test",
    "password_confirm": "test",
    "phone_number": "+213783961920",
    "user_type": "assistant",
    "service_type": "towing",
    "vehicle_type": "light",
    "current_lat" : 3423,
    "current_lng" : 222,
    "driving_license_cat": "b",
    "driving_license_num": 32434,
    "driving_license_expiry": "20:03:26",
    "vehicle_registration_num": 2343
}

###
POST http://localhost:8000/api/auth/verify-phone/ HTTP/1.1
Content-Type: application/json

{
    "phone_number" : "+213783072562"
}

###
POST http://localhost:8000/api/auth/verify-email/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MjA3Nzg4LCJpYXQiOjE3NDg2MDI5ODgsImp0aSI6IjlkN2I1ODJjMGIyODQ2MjFhMjNlNzU5YTQyNjhkOThjIiwidXNlcl9pZCI6MX0.044c8GhgTMOnJthdkjaMMo19f0Y0hPFMq3grN1Q6VGA

###

POST http://localhost:8000/api/auth/verify-email/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MjA3Nzg4LCJpYXQiOjE3NDg2MDI5ODgsImp0aSI6IjlkN2I1ODJjMGIyODQ2MjFhMjNlNzU5YTQyNjhkOThjIiwidXNlcl9pZCI6MX0.044c8GhgTMOnJthdkjaMMo19f0Y0hPFMq3grN1Q6VGA

###

POST http://localhost:8000/api/auth/verify-email/confirm/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MjA3Nzg4LCJpYXQiOjE3NDg2MDI5ODgsImp0aSI6IjlkN2I1ODJjMGIyODQ2MjFhMjNlNzU5YTQyNjhkOThjIiwidXNlcl9pZCI6MX0.044c8GhgTMOnJthdkjaMMo19f0Y0hPFMq3grN1Q6VGA

{
    "code" : 71230
}
###

POST http://localhost:8000/api/auth/password-reset/ HTTP/1.1
Content-Type: application/json

{
    "phone_number": "+213783072562"
}

###


POST http://localhost:8000/api/auth/password-reset/confirm/ HTTP/1.1
Content-Type: application/json

{
    "new_password" : "testing",
    "new_password_confirm" : "testing",
    "phone_number": "+213783072562",
    "code" : "84766"
}
###

POST http://localhost:8000/api/auth/login/phone/ HTTP/1.1
Content-Type: application/json

{
    "phone_number": "+213783072562",
    "password": "test0"
}

###

POST http://localhost:8000/api/auth/login/email/ HTTP/1.1
Content-Type: application/json

{
    "email": "assistant1@example.com",
    "password": "test"
}



### end assistance

Patch http://localhost:8000/api/assistance/update/end/44/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5NTUxMDM3LCJpYXQiOjE3NDg5NDYyMzcsImp0aSI6ImNhMDhmYzBmYTc5MjQxMjc5Njk1NTJlNTA0MTZjOGJhIiwidXNlcl9pZCI6NDl9.pl0lOlWz_ohhh0UBDfZZQ7cc6G35KjzPVtO-yk9QNoE

{
    "total_price" : 4000
}

### rating update

Patch http://localhost:8000/api/assistance/update/rating/9/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "rating" : "3.5"
}

###
GET http://localhost:8000/api/assistance/view/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTc2MDU3LCJpYXQiOjE3NDgzNzEyNTcsImp0aSI6IjNhYmRhYjg1N2Y5NjQ1ZDk4Mzg2OWYyZDU3MWY1YTM2IiwidXNlcl9pZCI6MjF9.jERb-hxATE3kF0en1iwa-a73-paDirT50VQ6LqGpIRQ