POST http://localhost:8000/api/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "name": "Mohammed0",
    "password": "test0",
    "password_confirm": "test0",
    "phone_number": "+213783072562",
    "user_type": "client"
}
###
POST http://localhost:8000/api/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "name": "Anes Adjal",
    "password": "test0",
    "password_confirm": "test0",
    "phone_number": "+213252526432",
    "user_type": "assistant",
    "service_type": "towing",
    "vehicle_type": "truck",
    "current_lat" : 37.4219983,
    "current_lng" : -122.084,
    "driving_license_cat": "c",
    "driving_license_num": 362328,
    "driving_license_expiry": "10:02:26",
    "vehicle_registration_num": 252621600
}

###
POST http://localhost:8000/api/auth/verify-phone/ HTTP/1.1
Content-Type: application/json

{
    "phone_number" : "+213783072562"
}

###
POST http://localhost:8000/api/auth/verify-email/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MjA3Nzg4LCJpYXQiOjE3NDg2MDI5ODgsImp0aSI6IjlkN2I1ODJjMGIyODQ2MjFhMjNlNzU5YTQyNjhkOThjIiwidXNlcl9pZCI6MX0.044c8GhgTMOnJthdkjaMMo19f0Y0hPFMq3grN1Q6VGA

###

POST http://localhost:8000/api/auth/verify-email/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MjA3Nzg4LCJpYXQiOjE3NDg2MDI5ODgsImp0aSI6IjlkN2I1ODJjMGIyODQ2MjFhMjNlNzU5YTQyNjhkOThjIiwidXNlcl9pZCI6MX0.044c8GhgTMOnJthdkjaMMo19f0Y0hPFMq3grN1Q6VGA

###

POST http://localhost:8000/api/auth/verify-email/confirm/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MjA3Nzg4LCJpYXQiOjE3NDg2MDI5ODgsImp0aSI6IjlkN2I1ODJjMGIyODQ2MjFhMjNlNzU5YTQyNjhkOThjIiwidXNlcl9pZCI6MX0.044c8GhgTMOnJthdkjaMMo19f0Y0hPFMq3grN1Q6VGA

{
    "code" : 71230
}
###

POST http://localhost:8000/api/auth/password-reset/ HTTP/1.1
Content-Type: application/json

{
    "phone_number": "+213783072562"
}

###


POST http://localhost:8000/api/auth/password-reset/confirm/ HTTP/1.1
Content-Type: application/json

{
    "new_password" : "testing",
    "new_password_confirm" : "testing",
    "phone_number": "+213783072562",
    "code" : "84766"
}
###

POST http://localhost:8000/api/auth/login/phone/ HTTP/1.1
Content-Type: application/json

{
    "phone_number": "0540",
    "password": "test"
}

###

POST http://localhost:8000/api/auth/login/email/ HTTP/1.1
Content-Type: application/json

{
    "email": "assistant1@example.com",
    "password": "test"
}

### view user profile
GET http://localhost:8000/api/profile/user/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDY2Mzc4LCJpYXQiOjE3NDg0NjE1NzgsImp0aSI6ImYxNDUwMjkxYWM4ODQ3MWNiNjgxOWNiZTY3MDA2YTljIiwidXNlcl9pZCI6Mn0.jbGl0Ful3dN6_Vtqu8XsAqpjKl1pIoDBbcTrnZg8rn4
### update user profile 'except password'
PUT http://localhost:8000/api/profile/user/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDY2Mzc4LCJpYXQiOjE3NDg0NjE1NzgsImp0aSI6ImYxNDUwMjkxYWM4ODQ3MWNiNjgxOWNiZTY3MDA2YTljIiwidXNlcl9pZCI6Mn0.jbGl0Ful3dN6_Vtqu8XsAqpjKl1pIoDBbcTrnZg8rn4

{
    "address" : "Setif-Algeria"
}

### update location
PUT http://localhost:8000/api/profile/update-location/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDY4NzkzLCJpYXQiOjE3NDg0NjM5OTMsImp0aSI6ImJjYTQxYjY2MjUzMDRlYTE5MjI3ODNjMDk2N2IxN2RjIiwidXNlcl9pZCI6Mn0.VKiEcPV_-LoMoyonbNiWJ3kl5Z5fAgiUb648Ffqz5z4

{
    "lat" :  34.052235,
    "lng" : -118.243683
}
### update status
PUT http://localhost:8000/api/profile/update-status/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDY5MjMyLCJpYXQiOjE3NDg0NjQ0MzIsImp0aSI6ImZlOGM3ODhhMTIwMzQ0ZTVhZmMzZDM2ZTMwYTMwY2U4IiwidXNlcl9pZCI6Nn0.nCz6xlZegzSkVQO-wFvv1FV1-VdS6QJCF1XiLjFOTt4

{
    "is_active" : true
}

### view assistant profile
GET http://localhost:8000/api/profile/assistant/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDY0NDY3LCJpYXQiOjE3NDg0NTk2NjcsImp0aSI6ImU5N2E1NjliNTk4MTRkMTJhYWNmYzk3NTc4YzA0ZWU4IiwidXNlcl9pZCI6NH0.pR3WCC2PHj5d5TdCLaCAawTUyT7DHSHgnU96bYaSaU4

### update assistant profile
PUT http://localhost:8000/api/profile/assistant/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDY0NDY3LCJpYXQiOjE3NDg0NTk2NjcsImp0aSI6ImU5N2E1NjliNTk4MTRkMTJhYWNmYzk3NTc4YzA0ZWU4IiwidXNlcl9pZCI6NH0.pR3WCC2PHj5d5TdCLaCAawTUyT7DHSHgnU96bYaSaU4

{
    "driving_license_expiry": "20:03:54"
}
###
get http://localhost:8000/api/assistants/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDY0NDY3LCJpYXQiOjE3NDg0NTk2NjcsImp0aSI6ImU5N2E1NjliNTk4MTRkMTJhYWNmYzk3NTc4YzA0ZWU4IiwidXNlcl9pZCI6NH0.pR3WCC2PHj5d5TdCLaCAawTUyT7DHSHgnU96bYaSaU4

### Assistance flow endpoints

POST http://localhost:8000/api/assistance/request/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5Mzc0Mzk1LCJpYXQiOjE3NDg3Njk1OTUsImp0aSI6IjQ0YTBlOGJlODY4ODRlNDc5Mzc1MmVjN2I0MmYyNmVkIiwidXNlcl9pZCI6NDZ9.6tbIVyHEdP-nMX0qRIUAwoLFIAO4k3kvbLZfI9Gxw9A

{
    "pickup": {
        "lat" : 37.431040706626916,
        "lng" : -122.08182524889709
    },
    "assistance_type": "repair",
    "dropoff": {
        "lat" : 37.431040706626916,
        "lng" : -122.08182524889709
    },
    "vehicle_type" : "light",
    "description": "A short desc."
}

###

Patch http://localhost:8000/api/assistance/accept/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MzE3NTE3LCJpYXQiOjE3NDg3MTI3MTcsImp0aSI6ImZhODMxODcwMTk1MzQ4MzM4Y2EyMGNmMWYwZTlkNGE5IiwidXNlcl9pZCI6NDN9.ZOVvB0GNArBZAHDeQmpiaEx7FYWZ9hPzcngM0bHkkmk

### assistant update
Patch http://localhost:8000/api/assistance/update/status/32/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MzE3NTE3LCJpYXQiOjE3NDg3MTI3MTcsImp0aSI6ImZhODMxODcwMTk1MzQ4MzM4Y2EyMGNmMWYwZTlkNGE5IiwidXNlcl9pZCI6NDN9.ZOVvB0GNArBZAHDeQmpiaEx7FYWZ9hPzcngM0bHkkmk

{
    "status" : "canceled"
}

### status update

Patch http://localhost:8000/api/assistance/update/status/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MzE3NTE3LCJpYXQiOjE3NDg3MTI3MTcsImp0aSI6ImZhODMxODcwMTk1MzQ4MzM4Y2EyMGNmMWYwZTlkNGE5IiwidXNlcl9pZCI6NDN9.ZOVvB0GNArBZAHDeQmpiaEx7FYWZ9hPzcngM0bHkkmk

{
    "status" : "completed"
}

### price update

Patch http://localhost:8000/api/assistance/update/price/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTc2MDU3LCJpYXQiOjE3NDgzNzEyNTcsImp0aSI6IjNhYmRhYjg1N2Y5NjQ1ZDk4Mzg2OWYyZDU3MWY1YTM2IiwidXNlcl9pZCI6MjF9.jERb-hxATE3kF0en1iwa-a73-paDirT50VQ6LqGpIRQ

{
    "price" : "1800.34"
}

### rating update

Patch http://localhost:8000/api/assistance/update/rating/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDI3MDMzLCJpYXQiOjE3NDg0MjIyMzMsImp0aSI6IjAzZTA3ZmMwMDEzYTRhN2FhYjdhOGFlNDBhM2Q1MTU1IiwidXNlcl9pZCI6MTh9.SzXlG2CLN6ZsBaZBvPwAA6C102zT-qHSUs9iMo0P4X4

{
    "rating" : "3.5"
}

###
GET http://localhost:8000/api/assistance/view/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTc2MDU3LCJpYXQiOjE3NDgzNzEyNTcsImp0aSI6IjNhYmRhYjg1N2Y5NjQ1ZDk4Mzg2OWYyZDU3MWY1YTM2IiwidXNlcl9pZCI6MjF9.jERb-hxATE3kF0en1iwa-a73-paDirT50VQ6LqGpIRQ